### ISSUE TITLE
UpdateArea

### ISSUE THREAD

**Issue by SamsamTS** [earalov/Skylines-SurfacePainter#1]
Hey PB,

Just a heads up. TerrainModify.UpdateArea should never be called outside of a SimulationStep routine, because of concurrency problem between threads. That's probably why you have the bug happen so randomly.

I hope this helps.

**Comment by earalov** [comment]
Aren't LoadingExtension's run in the same thread as simulation?

**Comment by SamsamTS** [comment]
I guess not. All updates must happen between BeginUpdate and EndUpdate. Only the simulation routines fall into that condition. I learnt it the hard way. Check where SimulationStep is called, I don't remember what the function is called, I'm on mobile right now so I cannot check.

**Comment by earalov** [comment]
Yeah, you're right. I'll fix this code to run the update in Simulation thread. I will also prevent the update from hiding props that were unhid with Prop Anarchy (requires change on its side too). Thanks for heads up!

**Comment by SamsamTS** [comment]
No problem man. Squish those bugs :)

**Comment by earalov** [comment]
@SamsamTS BTW, I'm making a mod of mine that allows editing spawn points and sub buildings right in asset editor:
https://github.com/earalov/Skylines-AdvancedBuildingsEdtior
It's almost ready but I still have to clean it up and add UI's for certain features. If you're interesting in contributing, just let me know.

**Comment by SamsamTS** [comment]
I'm quite busy with Move It yet and I proposed myself to provide Strictoaster help to improve Cinematic Camera (he hasn't responded yet). So I can't help you too much right now. If you have questions about UI I'll be happy to answer.

One of the major problem when doing UI in the editor is the access to the Ingame sprites. To do so you need to assign components the correct atlas. Here is a useful piece of code: https://github.com/SamsamTS/CS-MoveIt/blob/master/MoveIt/UIUtils.cs#L181-L199

That way you simply have to do `component.atlas = GetAtlas("Ingame");`

I hope this helps.

**Comment by earalov** [comment]
Should be fixed now
